export default {
  "allow-flight": false,
  "allow-nether": true,
  "broadcast-console-to-ops": true,
  "broadcast-rcon-to-ops": true,
  difficulty: "easy",
  "enable-command-block": false,
  "enable-jmx-monitoring": false,
  "enable-rcon": false,
  "sync-chunk-writes": true,
  "enable-status": true,
  "enable-query": false,
  "entity-broadcast-range-percentage": 100,
  "force-gamemode": false,
  "function-permission-level": 2,
  gamemode: "survival",
  "generate-structures": true,
  "generator-settings": null,
  hardcore: false,
  "level-name": "world",
  "level-seed": null,
  "level-type": "default",
  "max-players": 20,
  "max-tick-time": 60000,
  "max-world-size": 29999984,
  motd: "A Minecraft Server",
  "network-compression-threshold": 256,
  "online-mode": true,
  "op-permission-level": 4,
  "player-idle-timeout": 0,
  "prevent-proxy-connections": false,
  pvp: true,
  "query.port": 25565,
  "rate-limit": 0,
  "rcon.password": null,
  "rcon.port": 25575,
  "resource-pack": null,
  "resource-pack-prompt": null,
  "resource-pack-sha1": null,
  "require-resource-pack": false,
  "server-ip": null,
  "server-port": 25565,
  "simulation-distance": 10,
  "snooper-enabled": true,
  "spawn-animals": true,
  "spawn-monsters": true,
  "spawn-npcs": true,
  "spawn-protection": 16,
  "text-filtering-config": null,
  "use-native-transport": true,
  "view-distance": 10,
  "white-list": false,
  "enforce-whitelist": false,
} as {
  [keys: string]: unknown;
};
